require.config({
  baseUrl:"/",
  paths:{
    "header":"module/header",
    "footer":"module/footer",
    "slider":"module/slider",
    "jquery":"libs/jquery/jquery-1.11.3",
    "bootstrap":"libs/bootstrap/js/bootstrap",
    "tools":"libs/tools",
    "template":"libs/template-web",
    "cookie":"libs/jquery.cookie"
  },
  //垫片
  shims:{
    "bootstrap":{
      deps:["jquery"]
    }
  }
})
